In [13]:
import pandas as pd

df = pd.read_csv('datasets/ncaa_d1_player_deltas.csv')

df

,Unnamed: 0,index,conference,team,player,position,toi_(min),successful_oz_offensive_touches,failed_oz_offensive_touches,failed_oz_possessions,...,controlled_exit_with_play_after_rate,successful_defensive_dump-in_recoveries,failed_defensive_dump-in_recoveries,total_dump_out_attempts,dump_out_rate,successful_dump_out_attempts,total_icings,successful_oz_body_checks,successful_dz_body_checks,successful_body_checks
0,0,0,Independent,Stonehill College Skyhawks,Zach Aben,F,135:14,1.325179,1.546329,1.949394,...,-1.457838,1.736715,1.178641,-0.131162,-1.731198,-0.164045,1.770301,2.101965,1.340276,1.722580
1,1,1,Atlantic Hockey,College of the Holy Cross Crusaders,Michael Abgrall,F,534:41,0.727986,0.390310,0.267962,...,0.267067,-1.250064,-1.622353,-0.785673,-0.078183,-0.610080,-0.638005,0.268042,-0.843774,-0.664871
2,2,2,Big Ten,Ohio State University Buckeyes,Chris Able,D,601:37,-1.558633,-1.705093,-2.138877,...,-0.756475,2.040267,3.020268,2.716646,3.807273,2.867365,1.213134,-0.655342,-1.305897,-1.478943
3,3,3,CCHA,Michigan Tech University Huskies,Ryan Abraham,F,77:05,-0.997509,-1.024861,-1.347051,...,-1.116167,-1.877239,-2.304778,-2.407850,-1.438295,-2.485082,-1.219447,-1.706732,-2.035326,-2.401076
4,4,4,Independent,University of Alaska Anchorage Seawolves,Logan Acheson,D,616:58,1.938944,2.558493,2.803363,...,-0.393106,3.694705,2.940858,2.095940,-0.944100,1.963035,3.347329,1.205968,2.196348,2.195015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1543,1543,1543,NCHC,University of North Dakota Fighting Hawks,Bennett Zmolek,D,513:08,-2.194194,-1.719715,-1.675787,...,-0.569446,0.357819,0.273661,-1.271606,0.105487,-1.405361,-0.445948,0.223610,2.075029,2.088909
1544,1544,1544,Atlantic Hockey,Army Black Knights,Easton Zueger,D,509:06,-0.626929,-0.231749,-0.251846,...,-0.569508,0.369043,0.727270,1.392482,1.419485,1.406979,1.569833,-1.523953,1.039583,0.280000
1545,1545,1545,Hockey East,University of New Hampshire Wildcats,Conner de Haro,D,720:43,0.260333,-0.008740,0.032700,...,-0.901500,2.752881,2.692966,1.938664,0.606657,1.893655,2.282860,-1.025191,0.432274,-0.013461
1546,1546,1546,Atlantic Hockey,Robert Morris University Colonials,Luke van Why,D,593:08,0.189495,0.052922,-0.177588,...,0.905906,0.726752,0.246666,0.389062,0.649373,0.343439,0.465914,-1.523953,1.210798,0.752435
1547,1547,1547,Hockey East,UMass Minutemen,Lucas Ölvestad,D,827:21,0.347186,0.265388,0.181216,...,-0.050267,3.148244,3.707576,2.868662,1.191858,2.480435,5.279212,-1.025191,2.144417,1.561323

In [14]:
df = df.iloc[:, 2:]

df

,conference,team,player,position,toi_(min),successful_oz_offensive_touches,failed_oz_offensive_touches,failed_oz_possessions,successful_dz_offensive_touches,failed_dz_offensive_touches,...,controlled_exit_with_play_after_rate,successful_defensive_dump-in_recoveries,failed_defensive_dump-in_recoveries,total_dump_out_attempts,dump_out_rate,successful_dump_out_attempts,total_icings,successful_oz_body_checks,successful_dz_body_checks,successful_body_checks
0,Independent,Stonehill College Skyhawks,Zach Aben,F,135:14,1.325179,1.546329,1.949394,2.394185,1.948390,...,-1.457838,1.736715,1.178641,-0.131162,-1.731198,-0.164045,1.770301,2.101965,1.340276,1.722580
1,Atlantic Hockey,College of the Holy Cross Crusaders,Michael Abgrall,F,534:41,0.727986,0.390310,0.267962,-1.030919,-1.841551,...,0.267067,-1.250064,-1.622353,-0.785673,-0.078183,-0.610080,-0.638005,0.268042,-0.843774,-0.664871
2,Big Ten,Ohio State University Buckeyes,Chris Able,D,601:37,-1.558633,-1.705093,-2.138877,1.876218,2.197556,...,-0.756475,2.040267,3.020268,2.716646,3.807273,2.867365,1.213134,-0.655342,-1.305897,-1.478943
3,CCHA,Michigan Tech University Huskies,Ryan Abraham,F,77:05,-0.997509,-1.024861,-1.347051,-1.963637,-2.170602,...,-1.116167,-1.877239,-2.304778,-2.407850,-1.438295,-2.485082,-1.219447,-1.706732,-2.035326,-2.401076
4,Independent,University of Alaska Anchorage Seawolves,Logan Acheson,D,616:58,1.938944,2.558493,2.803363,5.072106,4.433355,...,-0.393106,3.694705,2.940858,2.095940,-0.944100,1.963035,3.347329,1.205968,2.196348,2.195015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1543,NCHC,University of North Dakota Fighting Hawks,Bennett Zmolek,D,513:08,-2.194194,-1.719715,-1.675787,0.307819,-0.260287,...,-0.569446,0.357819,0.273661,-1.271606,0.105487,-1.405361,-0.445948,0.223610,2.075029,2.088909
1544,Atlantic Hockey,Army Black Knights,Easton Zueger,D,509:06,-0.626929,-0.231749,-0.251846,-0.330704,0.281023,...,-0.569508,0.369043,0.727270,1.392482,1.419485,1.406979,1.569833,-1.523953,1.039583,0.280000
1545,Hockey East,University of New Hampshire Wildcats,Conner de Haro,D,720:43,0.260333,-0.008740,0.032700,1.688992,2.618802,...,-0.901500,2.752881,2.692966,1.938664,0.606657,1.893655,2.282860,-1.025191,0.432274,-0.013461
1546,Atlantic Hockey,Robert Morris University Colonials,Luke van Why,D,593:08,0.189495,0.052922,-0.177588,0.070182,-0.456701,...,0.905906,0.726752,0.246666,0.389062,0.649373,0.343439,0.465914,-1.523953,1.210798,0.752435
1547,Hockey East,UMass Minutemen,Lucas Ölvestad,D,827:21,0.347186,0.265388,0.181216,2.661810,3.369468,...,-0.050267,3.148244,3.707576,2.868662,1.191858,2.480435,5.279212,-1.025191,2.144417,1.561323

In [16]:
df.to_csv("datasets/ncaa_d1_player_deltas_cleaned.csv", index=False)